---
title: "Final Reflection"
format: docx
editor: visual
code-fold: true
smooth-scroll: true
theme: mint
---

## Introduction {style="color: darkblue"}

Over all I think I have earned a B+ in this course. I turn in most of my labs on time, I demonstrated proficiency in the majority of the learning targets, I contributed to my group in class and over text, I revised a majority of my labs, and I try to extend my thinking within in the assignments and I extend my thinking by taking the objectives achieved in this course and applying it to my thesis work. I was able to extend what I learned in this course to drastically shorten the time it took me to process data from my research in for my thesis and reduced the time it took me to create and format figures which I am including in my final draft of my thesis. By extending my thinking to tasks beyond what is included in the assignments in this course I have become a better critical thinker when it comes mapping which approach is the most efficient for cleaning data. Overall I think I have shown a commitment to understanding the learning objectives, helping my peers, and thinking critically about how applications of each learning target to deserve a B+ in this course.

## Meeting Learning Targets {style="color: darkblue"}

WD-1 is demonstrated by data_import_practice.qmd; WD-2 was met by lab4 problem 3.2 and 4.2; WD-3 was met by problem 2.A of PA3; WD-4 is met by step 4 of PA3, problem 4 of lab 3, and problem 3 of lab5; WD-6 was met by problem 3.3 of lab4; WD-7 is met by problems 4 and 4.2 in lab4; R-1 was demonstrated by the htm out put of lab4; R-2 was met by lab7 part; R-3 was demonstrated by lab 7 part 2 c; DVS-1 was met by problems 1, 2, and 3 of lab5; DVS-2 was met problem 1 of lab 5, and problem 4.2 of lab 4; DVS-3 was me by both problem 2 of lab4_challenge #2, and lab5 #1; DVS-4 was demonstrated in lab4_challenge #1, and by part 7 of lab3; DVS-5 was met by the datatable in lab 9 and lab 3 number 7; PE-1, PE-2, and PE-2 were met by lab8's large test problem, and lab4's problems 3.1 and 3.2; PE-3 and PE-4 were met by lab4_challenge problem 1, and lab 8 Use You Function; DSM-1 was met by PA9 problem 3; DSM-2 is met by lab 9 problems 3.2 and 4, as well as, PA9 problem 1.

## Extending My Learning {style="color: darkblue"}

I think I have come a long way in my creativity of graphs. I use a lot more colors now, I will choose my lay out based on if I will have a common legend. I use `#| layout_ncol`: if there will not be a common legend, but I will use `ggarrange( )` if there will be a common legend. I default to using using the hash pipe method by lab4_challenge problem 2 is an instance I used ggarrange( ) to create a common legend.

I am also proud of the skills from this course that I been able to take into my research work here at cal poly. I developed an array of functions to reduce the amount of time it takes me to process data, and I have used many of the ggplot skills learned in this class to create visualizations. In my thesis.qmd found in the continued learning folder in supporting artifacts, I use the functions to process data from an instrument I commonly use to create a visual and a plot in 1, and in 1.2 I create a visual with the ggplot skills and create a table using the pivot skills.

Through my continued learning I believe I have demonstrated that I am often thinking critically about the material in this course. Also, that I am exemplifying the outcome of this course to be a adept user of R and R studio.
