---
title: "Course Work Demonstration"
format: docx
editor: visual
code-fold: true
smooth-scroll: true
theme: mint
engine: knitr
---

## 

+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------+
| ### **Working with Data** {style="color:darkblue"}                                                                                                                   | ### **Data Visualization & Summarization**  {style="color: darkblue"}                 |
|                                                                                                                                                                      |                                                                                       |
| -   **WD-1:** I can import data from a variety of formats (e.g., csv, xlsx, txt, etc.).                                                                              | -   **DVS-1:** I can create visualizations for                                        |
|                                                                                                                                                                      |     a variety of variable types(e.g., numeric, character, factor, date)               |
| -   **WD-2:** I can select necessary columns from a dataset.                                                                                                         |                                                                                       |
|                                                                                                                                                                      | -   **DVS-2:** I use plot modifications to make my visualization clear to the reader. |
| -   **WD-3:** I can filter rows from a dataframe for a variety of data types (e.g., numeric, integer, character, factor, date).                                      |                                                                                       |
|                                                                                                                                                                      | -   **DVS-3:** I show creativity in my visualizations                                 |
| -   **WD-4:** I can modify existing variables and create new variables in a dataframe for a variety of data types (e.g., numeric, integer, character, factor, date). |                                                                                       |
|                                                                                                                                                                      | -   **DVS-4:** I can calculate numerical                                              |
| -   **WD-5:** I can use mutating joins to combine multiple dataframes.                                                                                               |     summaries of variables.                                                           |
|                                                                                                                                                                      |                                                                                       |
| -   **WD-6:** I can use filtering joins to filter rows from a dataframe.                                                                                             | -   **DVS-5:** I can find summaries of                                                |
|                                                                                                                                                                      |     variables across multiple groups.                                                 |
| -   **WD-7:** I can pivot dataframes from long to wide and visa versa.                                                                                               |                                                                                       |
|                                                                                                                                                                      | -   **DVS-6:** I can create tables which make my summaries clear to                   |
| ### **Reproducibility** {style="color: darkblue"}                                                                                                                    |     the reader.                                                                       |
|                                                                                                                                                                      |                                                                                       |
| -   **R-1:** I can create professional looking, reproducible                                                                                                         | -   **DVS-7:** I show creativity in my tables.                                        |
|     analyses using RStudio projects, Quarto documents, and the here package.                                                                                         |                                                                                       |
|                                                                                                                                                                      | ### **Program Efficiency** {style="color: darkblue"}                                  |
| -   **R-2:** I can write well documented and tidy code                                                                                                               |                                                                                       |
|                                                                                                                                                                      | -   **PE-1:** I can write concise code which does not repeat itself.                  |
| -   **R-3:** I can write robust programs that are resistant to changes in inputs.                                                                                    |                                                                                       |
|                                                                                                                                                                      | -   **PE-2:** I can write functions to reduce repetition in my code.                  |
|                                                                                                                                                                      |                                                                                       |
|                                                                                                                                                                      | -   **PE-3:**I can use iteration to reduce repetition in my code.                     |
|                                                                                                                                                                      |                                                                                       |
|                                                                                                                                                                      | -   **PE-4:** I can use modern tools when carrying out my analysis.                   |
|                                                                                                                                                                      |                                                                                       |
|                                                                                                                                                                      | ### **Data Simulation & Modeling** {style="color: darkblue"}                          |
|                                                                                                                                                                      |                                                                                       |
|                                                                                                                                                                      | -   **DSM-1:** I can simulate data from a variety of probability models.              |
|                                                                                                                                                                      |                                                                                       |
|                                                                                                                                                                      | -   **DSM-2:** I can fit a linear regression and extract necessary summary measures.  |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------+

## Meeting Learning Targets {style="color: darkblue"}

WD-1 is demonstrated by data_import_practice.qmd; WD-2 was met by lab4 problem 3.2 and 4.2; WD-3 was met by problem 2.A of PA3; WD-4 is met by step 4 of PA3, problem 4 of lab 3, and problem 3 of lab5; WD-6 was met by problem 3.3 of lab4; WD-7 is met by problems 4 and 4.2 in lab4; R-1 was demonstrated by the htm out put of lab4; R-2 was met by lab7 part; R-3 was demonstrated by lab 7 part 2 c; DVS-1 was met by problems 1, 2, and 3 of lab5; DVS-2 was met problem 1 of lab 5, and problem 4.2 of lab 4; DVS-3 was me by both problem 2 of lab4_challenge #2, and lab5 #1; DVS-4 was demonstrated in lab4_challenge #1, and by part 7 of lab3; DVS-5 was met by the datatable in lab 9 and lab 3 number 7; PE-1, PE-2, and PE-2 were met by lab8's large test problem, and lab4's problems 3.1 and 3.2; PE-3 and PE-4 were met by lab4_challenge problem 1, and lab 8 Use You Function; DSM-1 was met by PA9 problem 3; DSM-2 is met by lab 9 problems 3.2 and 4, as well as, PA9 problem 1.\
\

\
\
