---
title: "Practice Activity 9.1: Regression"
format: 
  html:
    self-contained: true
editor: visual
execute: 
  warning: false
  messages: false
theme: mint
code-fold: true
---

# 

```{r}
library(tidyverse)
animals <- read_csv(here::here("supporting_artifacts", "ref.work", "PA9", "mystery_animal.csv"))
str(animals)
```

# 1

```{r}
animals_lm <- animals |> lm(weight_after ~ weight_before, data = _)

tbl <- broom::augment(animals_lm)

tbl |> ggplot(mapping = aes(x = weight_before, y = .resid)) +
  geom_point(color = "darkred")
```

# 2

warm up

```{r}
#trumpet percentile 
qunif(0.95, 1.5, 3.5)

# 10th percentile trambone weight
qnorm(0.1, mean = 4.6, sd = 0,8)

# percent of trabones that weight more than 5 pounds
1 - pnorm(5, mean = 4.6, sd = 0.8)

# percent of reed instruments that weight more than 5 pounds
1 - pchisq(5, df = 4)

#number of trambones less than 4 poounds in random sample of 100
trambones <- rnorm(100, mean = 4.6, sd = 0.8)

sum(trambones < 4)
```

# 3

```{r}
music_man <- function(n_tromb, n_cor, n_reed){
  
  trombones <- rnorm(n_tromb, mean = 4.6, sd = 0.8)
  cornets <- runif(n_cor, 1.5, 3.5)
  reeds <- rchisq(n_reed, df = 4)
  
  return(sum(trombones, cornets, reeds))
  
}

set.seed(1957)

my_weights <- rerun(.n = 1000, 
                    music_man(n_tromb = 76, n_cor = 110, n_reed = 1035)
                    ) |> 
  flatten_dbl()

sum(my_weights < 4532)

```
