---
title: "lab5"
format: 
  html:
    self-contained: true
editor: visual
code-fold: true
execute: 
  warning: false
  error: true
theme: mint
fig-align: center
---

## 1. revisit lab 2

```{r setup, include = FALSE}
library(tidyverse)
library(forcats)
library(lubridate)
```

```{r data, include = FALSE}
surveys <- read_csv(here::here("supporting_artifacts","ref.work", 
                               "Lab5","surveys.csv"))
```

```{r speicie.V.weight}
surveys |> 
  ggplot(
    data = surveys,
         mapping = 
           aes(y = fct_reorder(species, weight, .desc = FALSE),
               x = weight)
    ) +
  geom_jitter(mapping = aes(color = species), 
              alpha = .1, show.legend = FALSE) +
  geom_boxplot(outlier.shape = NA) +
  labs(title = "Distribution of Weight by Species", y = NULL)
```

## 2.Time-Series Plot

```{r time_series}
surveys_clean <- surveys |> 
  mutate(year = year(date)) |> 
  group_by(genus, year) |> 
  summarise(mean_wt = mean(weight), .keep_all = TRUE) |> 
  ungroup()

surveys_clean |> 
  ggplot(mapping = aes(year, mean_wt, color = fct_reorder2(genus, year, mean_wt))) +
  geom_line() +
  labs(color = "Genus")+
  ylab("mean weight (g)") +
  ggtitle("Time Series of Genus Weight in Years") +
  theme(legend.box.background = element_rect(fill = "grey"))
  

```

## 3.Captures of the Week

```{r daily_comparison}
day_levels <- 
  c("Mon","Tue", "Wed", "Thu", "Fri", "Sat", "Sun" )

surveys_clean <- surveys |> 
  mutate(date = make_date(date),
         days = wday(date, label = TRUE)) |>
  select(taxa, days) |> 
  group_by(days) |> 
  summarize(captures = n()) |> 
  filter(days != "NA")

surveys_clean |> 
  ggplot(
    mapping = aes(fct_relevel(days, day_levels), captures,
                  fill = fct_relevel(days, day_levels))
    ) +
  geom_col(show.legend = FALSE) +
  scale_x_discrete(drop = TRUE)+
  coord_flip() +
  labs(y = "Number of Rodents Captured", x = NULL)
  
```

## 2. weekend

```{r weekend}
surveys_clean <- surveys_clean |> 
  mutate(days = fct_collapse(days, 
                             weekdays = c("Mon","Tue", "Wed",
                                          "Thu", "Fri"),
                             weekend = c("Sat", "Sun"))) |> 
  group_by(days) |> 
  summarise(AverageCaptures = mean(captures))

surveys_clean |> 
  ggplot(mapping = aes(
    fct_reorder(days, AverageCaptures, .desc = FALSE),
    AverageCaptures)) +
  geom_col(fill = c("blue", "yellow")) +
  scale_x_discrete(drop = TRUE) +
  coord_flip() +
  labs(caption = "weekend = saturday + sunday", 
       y = "Mean Number of Rodents Captured Per Day",
       x = NULL)
```
